---
abstract: 'lookup on nested data with simple path notation'
author:
  - 'Scott Beck <scottbeck@gmail.com>'
build_requires:
  English: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101550, CPAN::Meta::Converter version 2.101610'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-SPath
requires:
  Carp: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Text::Balanced: 0
  perl: 5.010_000
resources:
  repository: git://github.com/bline/data-spath.git
version: 0.0004
